---
substitutions:
  name: econet-water-heater
  friendly_name: "Water Heater"
  # M5Stack ATOMS3 Lite + ATOMIC RS485 Base pin mapping
  tx_pin: GPIO6
  rx_pin: GPIO5

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: m5stack-atoms3
  variant: esp32s3
  framework:
    type: arduino

packages:
  econet:
    url: https://github.com/esphome-econet/esphome-econet
    ref: v3.4.0
    file: econet_heatpump_water_heater.yaml

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome

logger:
  level: WARN
